# BevNet, Entire dataset
splits:
  train: train
  valid: mini_train
  test : mini_test

actor: BevNet
epochs: 1000
horizon: 50
self_supervised: False

reinitialize_network: False
hard_example_mining: False
buffer_size: 25000  # (200 samples_per_epoch) * (50 epochs)
batch_size: 200
valid_ratio: 0.25

# behavior cloning
samples_for_bc: 200
batches_for_bc: 100

# aggregation epoch
samples_per_epoch: 200
batches_per_epoch: 100

# training parameters
learning_rate: 3.0e-5
metric: Huber
optimizer: adam
eval_every: 10
