# CNN1D, Scene 5
splits:
  train: scene5
  valid: scene5
  test : null

actor: CNN1D
epochs: 500
horizon: 30  # 50
self_supervised: False

reinitialize_network: False
hard_example_mining: False
buffer_size: 50000  # ~ epochs * samples_per_epoch
batch_size: 500
valid_ratio: 0.25

# behavior cloning
samples_for_bc: 500
batches_for_bc: 500

# aggregation epoch
samples_per_epoch: 100
batches_per_epoch: 500

# training parameters
learning_rate: 3.0e-5
metric: Huber
optimizer: adam
eval_every: 1  # 20
